/* ==========================================================
   Path and File: ./test.js
   Description: Complete Test Suite for LunaDB Client (with Timing)
   ========================================================== */

import { LunaDBClient } from "../lunadb-client.js";
import assert from "node:assert";
import { performance } from "node:perf_hooks";

// ---------------------------------------------------------
// HELPERS FOR VALIDATION AND VISUALIZATION
// ---------------------------------------------------------
async function runTest(testName, testFn) {
  process.stdout.write(`⏳ Testing: ${testName.padEnd(50, ".")} `);
  try {
    const start = performance.now();
    await testFn();
    const end = performance.now();
    const duration = (end - start).toFixed(2);
    console.log(`✅ OK (${duration}ms)`);
  } catch (err) {
    console.log("❌ FAILED");
    console.error(`\nError details in [${testName}]:`);
    console.error(err);
    process.exit(1); // Stop everything if a core test fails
  }
}

// ==========================================
// TEST EXECUTION
// ==========================================
async function main() {
  console.log("\n=======================================================");
  console.log(" 🧪 STARTING COMPLETE TEST SUITE: LunaDB Client 🧪 ");
  console.log("=======================================================\n");

  const client = new LunaDBClient("localhost", 5876, "admin", "adminpass", null, false);
  const runId = Date.now();
  const testCol = `test_collection_${runId}`;
  const joinCol = `test_join_${runId}`;

  // ---------------------------------------------------------
  // PHASE 1: Connection and Authentication
  // ---------------------------------------------------------
  await runTest("1. TLS Connection and Authentication", async () => {
    await client.connect();
    assert.strictEqual(client.isAuthenticatedSession, true, "Client should be authenticated");
    assert.strictEqual(client.authenticatedUser, "admin", "User should be 'admin'");
  });

  // ---------------------------------------------------------
  // PHASE 2: Collection Management
  // ---------------------------------------------------------
  await runTest("2. Create Collections", async () => {
    await client.collectionCreate(testCol);
    await client.collectionCreate(joinCol);
  });

  await runTest("3. List Collections", async () => {
    const list = await client.collectionList();
    assert.ok(Array.isArray(list), "The collection list must be an array");
    assert.ok(list.includes(testCol), `The list must include ${testCol}`);
  });

  // ---------------------------------------------------------
  // PHASE 3: Index Management
  // ---------------------------------------------------------
  await runTest("4. Create Indexes", async () => {
    await client.collectionIndexCreate(testCol, "username");
    await client.collectionIndexCreate(testCol, "age");
  });

  await runTest("5. List Indexes", async () => {
    const indexes = await client.collectionIndexList(testCol);
    assert.ok(indexes.includes("username"), "The 'username' index must exist");
    assert.ok(indexes.includes("age"), "The 'age' index must exist");
    assert.ok(indexes.includes("_id"), "The default '_id' index must exist");
  });

  await runTest("6. Delete Indexes", async () => {
    await client.collectionIndexDelete(testCol, "username");
    const indexes = await client.collectionIndexList(testCol);
    assert.ok(!indexes.includes("username"), "The 'username' index should have been deleted");
  });

  // ---------------------------------------------------------
  // PHASE 4: Item CRUD (Single)
  // ---------------------------------------------------------
  let autoGeneratedId = "";

  await runTest("7. Insert an Item (Set) with and without Key", async () => {
    // With explicit Key
    await client.collectionItemSet(testCol, { name: "Juan", age: 30 }, "user_1");
    
    // Without Key (Auto-generated by the server)
    const res = await client.collectionItemSet(testCol, { name: "Pedro", age: 25 });
    assert.ok(res._id, "The server should have returned an auto-generated _id");
    autoGeneratedId = res._id;
  });

  await runTest("8. Read an Item (Get)", async () => {
    const res = await client.collectionItemGet(testCol, "user_1");
    assert.strictEqual(res.found, true);
    assert.strictEqual(res.value.name, "Juan");
    assert.strictEqual(res.value.age, 30);
  });

  await runTest("9. Update an Item (Update)", async () => {
    await client.collectionItemUpdate(testCol, "user_1", { age: 31, city: "Madrid" });
    const res = await client.collectionItemGet(testCol, "user_1");
    assert.strictEqual(res.value.age, 31, "The age should have changed");
    assert.strictEqual(res.value.city, "Madrid", "The new field should have been added");
    assert.strictEqual(res.value.name, "Juan", "The original name should not have been deleted");
  });

  await runTest("10. Delete an Item (Delete)", async () => {
    await client.collectionItemDelete(testCol, autoGeneratedId);
    const res = await client.collectionItemGet(testCol, autoGeneratedId);
    assert.strictEqual(res.found, false, "The auto-generated item should have been deleted");
  });

  // ---------------------------------------------------------
  // PHASE 5: Item CRUD (Batch / Mass)
  // ---------------------------------------------------------
  await runTest("11. Insert Multiple Items (Set Many)", async () => {
    const items = [
      { _id: "user_10", name: "Ana", age: 28, role: "admin" },
      { _id: "user_11", name: "Luis", age: 35, role: "user" },
      { _id: "user_12", name: "Maria", age: 22, role: "user" }
    ];
    await client.collectionItemSetMany(testCol, items);
  });

  await runTest("12. Update Multiple Items (Update Many)", async () => {
    const patches = [
      { _id: "user_10", patch: { role: "superadmin" } },
      { _id: "user_12", patch: { age: 23 } }
    ];
    await client.collectionItemUpdateMany(testCol, patches);
    
    const ana = await client.collectionItemGet(testCol, "user_10");
    const maria = await client.collectionItemGet(testCol, "user_12");
    assert.strictEqual(ana.value.role, "superadmin");
    assert.strictEqual(maria.value.age, 23);
  });

  await runTest("13. Delete Multiple Items (Delete Many)", async () => {
    await client.collectionItemDeleteMany(testCol, ["user_10", "user_11"]);
    const res10 = await client.collectionItemGet(testCol, "user_10");
    const res11 = await client.collectionItemGet(testCol, "user_11");
    assert.strictEqual(res10.found, false);
    assert.strictEqual(res11.found, false);
  });

  // ---------------------------------------------------------
  // PHASE 6: Query Engine
  // ---------------------------------------------------------
  await runTest("14. Queries (Filters, Limit, OrderBy)", async () => {
    // Populate data for the test
    await client.collectionItemSetMany(testCol, [
      { _id: "q1", v: 10, cat: "A" }, { _id: "q2", v: 50, cat: "A" },
      { _id: "q3", v: 30, cat: "B" }, { _id: "q4", v: 40, cat: "A" }
    ]);

    const results = await client.collectionQuery(testCol, {
      filter: { field: "cat", op: "=", value: "A" },
      order_by: [{ field: "v", direction: "desc" }],
      limit: 2
    });

    assert.strictEqual(results.length, 2);
    assert.strictEqual(results[0].v, 50);
    assert.strictEqual(results[1].v, 40);
  });

  await runTest("15. Queries (Aggregations and Group By)", async () => {
    const results = await client.collectionQuery(testCol, {
      group_by: ["cat"],
      aggregations: { 
        total_v: { func: "sum", field: "v" },
        count_docs: { func: "count", field: "*" } 
      }
    });

    const catA = results.find(r => r.cat === "A");
    assert.ok(catA, "Group A must exist");
    assert.strictEqual(catA.total_v, 100); // 10 + 50 + 40
    assert.strictEqual(catA.count_docs, 3);
  });

  await runTest("16. Queries (Lookups / Joins)", async () => {
    await client.collectionItemSet(joinCol, { desc: "Category A Details" }, "A");
    const results = await client.collectionQuery(testCol, {
      filter: { field: "_id", op: "=", value: "q1" },
      lookups: [{ from: joinCol, localField: "cat", foreignField: "_id", as: "join_data" }]
    });

    assert.strictEqual(results[0].join_data.desc, "Category A Details", "The cross join should work");
  });

  // ---------------------------------------------------------
  // PHASE 7: ACID Transactions (Stateful)
  // ---------------------------------------------------------
  await runTest("17. Transactions: Commit", async () => {
    // 1. Prepare the ground: create an item outside the transaction
    await client.collectionItemSet(testCol, { state: "initial" }, "tx_1");

    // 2. Start the transaction
    const tx = await client.begin();
    
    // 3. Modify the existing item and create a new one
    await tx.collectionItemUpdate(testCol, "tx_1", { state: "tx_done" });
    await tx.collectionItemSet(testCol, { state: "new" }, "tx_new");

    // 4. Verify isolation: the changes should NOT be applied YET
    const resBefore = await client.collectionItemGet(testCol, "tx_1");
    assert.strictEqual(resBefore.value.state, "initial", "State should not have changed before commit");

    // 5. Commit the transaction
    await tx.commit();

    // 6. Verify that NOW they are applied to the disk
    const resAfterUpdate = await client.collectionItemGet(testCol, "tx_1");
    assert.strictEqual(resAfterUpdate.value.state, "tx_done", "State should have changed after commit");

    const resAfterNew = await client.collectionItemGet(testCol, "tx_new");
    assert.strictEqual(resAfterNew.found, true, "The new item should have been saved after commit");
  });

  await runTest("18. Transactions: Rollback", async () => {
    const tx = await client.begin();
    
    // Attempt to delete the existing record and create a new one
    await tx.collectionItemDelete(testCol, "tx_1"); 
    await tx.collectionItemSet(testCol, { state: "should_not_exist" }, "tx_2");
    
    // Cancel the transaction
    await tx.rollback();

    // Verify that the changes were NOT applied to the disk
    const res2 = await client.collectionItemGet(testCol, "tx_2");
    assert.strictEqual(res2.found, false, "The Set inside the cancelled tx should not have been saved");

    const res1 = await client.collectionItemGet(testCol, "tx_1");
    assert.strictEqual(res1.found, true, "The Delete inside the cancelled tx should not have been applied");
  });

  // ---------------------------------------------------------
  // PHASE 8: Cleanup and Close
  // ---------------------------------------------------------
  await runTest("19. Delete Collections (Drop)", async () => {
    await client.collectionDelete(testCol);
    await client.collectionDelete(joinCol);
    
    const list = await client.collectionList();
    assert.ok(!list.includes(testCol), "The test collection should have been deleted");
  });

  console.log("\n=======================================================");
  console.log(" 🎉 ALL TESTS PASSED SUCCESSFULLY! 🎉 ");
  console.log(" The LunaDB Node.js client is 100% functional.");
  console.log("=======================================================\n");

  client.close();
}

main();